version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    networks:
      - backend
  frontend:
    build: ./frontend
    ports: 
      - "8080:3000"
    networks:
      - frontend
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  backend:
    build: ./lib_catalog
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/admin || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"



    
